module RbsActiveHash
  module ActiveHash
    module Parser
      class AssociationDefinition < RBS::AST::Members::Include
      end

      class RB < RBS::Prototype::RB
      end

      class Parser
        attr_reader has_many: Array[[Symbol, Hash[untyped, untyped]]]
        attr_reader has_one: Array[[Symbol, Hash[untyped, untyped]]]
        attr_reader belongs_to: Array[[Symbol, Hash[untyped, untyped]]]

        def initialize: () -> void
        def parse: (String string, Array[Symbol] target) -> void
        def process: (RBS::AST::Declarations::t | RBS::AST::Members::t node, Array[Symbol] target) -> void
        def process_association_definition: (AssociationDefinition node) -> void
        def node_to_literal: (untyped node) -> untyped
      end
    end
  end
end
