module Rake
  class TaskLib
    include Rake::DSL
  end

  module DSL
    private

    def desc: (String description) -> void
    def file: (*untyped args) ?{ () -> void } -> void
    def import: (*String fns) -> void
    def multitask: (*untyped args) ?{ () -> void } -> void
    def namespace: (?String? name) ?{ () -> void } -> void
    def rule: (*untyped args) ?{ () -> void } -> void
    def task: (*untyped args) ?{ () -> void } -> void
    def sh: (*String cmd) ?{ (bool, Process::Status) -> void } -> void
  end
end

